const ROBOTS={Zhort:{color:'#46a5ff',rgb:'70,165,255',initial:'Z'},Rios:{color:'#6ddb9a',rgb:'109,219,154',initial:'R'},Vendra:{color:'#ffad5e',rgb:'255,173,94',initial:'V'}};
const storeKey='zrv-lap-sessions';
const state={robot:localStorage.getItem('zrv-robot')||'Zhort',screen:'home',running:false,startedAt:0,elapsed:0,laps:[],raf:0,sound:localStorage.getItem('zrv-sound')!=='off',historyFilter:'all',video:{stream:null,recorder:null,chunks:[],cameraOn:false,running:false,waitingForStart:true,startedAt:0,elapsed:0,laps:[],lastFrame:null,lastDetection:0,raf:0,line:.5,facing:'environment'}};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function format(ms){const total=Math.max(0,Math.round(ms));const m=Math.floor(total/60000);const s=Math.floor(total%60000/1000);const t=total%1000;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${String(t).padStart(3,'0')}`}
function sessions(){try{return JSON.parse(localStorage.getItem(storeKey)||'[]')}catch{return[]}}
function saveSessions(data){localStorage.setItem(storeKey,JSON.stringify(data))}
function robotPill(el){const r=ROBOTS[state.robot];el.innerHTML=`<i style="background:${r.color}"></i><span>${state.robot}</span>`;el.style.color=r.color;el.style.background=`rgba(${r.rgb},.12)`}
function renderRobots(){const wrap=$('#robot-selector');wrap.innerHTML=Object.entries(ROBOTS).map(([name,r])=>`<button type="button" class="robot-card ${name===state.robot?'selected':''}" style="--robot:${r.color};--robot-rgb:${r.rgb}" data-robot="${name}"><span class="robot-orb">${r.initial}</span><strong>${name}</strong><small>${name==='Zhort'?'Azul':name==='Rios'?'Verde':'Laranja'}</small></button>`).join('');$$('[data-robot]').forEach(b=>b.onclick=()=>{state.robot=b.dataset.robot;localStorage.setItem('zrv-robot',state.robot);renderRobots();updateRobotUI();toast(`${state.robot} selecionado`);});}
function updateRobotUI(){['#manual-robot-pill','#video-robot-pill'].forEach(s=>robotPill($(s)));const r=ROBOTS[state.robot];document.documentElement.style.setProperty('--accent',r.color);document.documentElement.style.setProperty('--accent-rgb',r.rgb);renderHomeStats()}
function renderHomeStats(){const all=sessions();$('#home-stats').textContent=all.length?`${all.length} sessão${all.length>1?'ões':''} salva${all.length>1?'s':''} neste aparelho`:'NENHUMA SESSÃO SALVA AINDA'}
function showScreen(name){state.screen=name;$$('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===name));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.go===name||(name==='manual'&&b.classList.contains('central'))));if(name==='history')renderHistory();if(name==='compare')renderComparison();if(name==='home')renderHomeStats();if(name!=='video'&&state.video.running)stopVideoSession(false);window.scrollTo({top:0,behavior:'smooth'})}
function updateTimer(){const now=state.running?performance.now()-state.startedAt:state.elapsed;const display=format(now);$('#timer-display').innerHTML=display.slice(0,-4)+`<span>${display.slice(-4)}</span>`;$('#timer-total').textContent=display;$('#timer-status').textContent=state.running?'CRONOMETRANDO':(state.elapsed?'PAUSADO':'PRONTO');$('#timer-status-dot').classList.toggle('running',state.running);$('#timer-lap-count').textContent=`${state.laps.length} VOLTA${state.laps.length===1?'':'S'}`;$('#start-pause').querySelector('span').textContent=state.running?'Ⅱ':'▶';$('#start-pause').querySelector('strong').textContent=state.running?'Pausar':'Iniciar';$('#lap-button').disabled=!state.running;$('#save-session-button').disabled=state.laps.length===0;if(state.running)state.raf=requestAnimationFrame(updateTimer)}
function startPause(){if(state.running){state.elapsed=performance.now()-state.startedAt;state.running=false;cancelAnimationFrame(state.raf)}else{state.startedAt=performance.now()-state.elapsed;state.running=true}updateTimer()}
function recordLap(){if(!state.running)return;const total=performance.now()-state.startedAt;const previous=state.laps.reduce((a,l)=>a+l.duration,0);state.laps.push({duration:total-previous,total});renderLaps();beep()}
function renderLaps(){const list=$('#laps-list');if(!state.laps.length){list.innerHTML='<div class="empty-state"><span>＋</span><p>Inicie o cronômetro e toque em<br><strong>Volta</strong> ao cruzar a linha.</p></div>';$('#laps-best').textContent='MELHOR —';return}const best=Math.min(...state.laps.map(l=>l.duration));$('#laps-best').textContent=`MELHOR ${format(best)}`;list.innerHTML=[...state.laps].reverse().map((l,i)=>`<div class="lap-row ${l.duration===best?'best':''}"><span class="lap-number">#${state.laps.length-i}</span><span class="lap-time">${format(l.duration)}</span>${l.duration===best?'<span class="best-label">MELHOR</span>':''}</div>`).join('')}
function resetTimer(){state.running=false;cancelAnimationFrame(state.raf);state.elapsed=0;state.laps=[];updateTimer();renderLaps()}
function saveSession(laps=state.laps,type='manual',total=state.laps.reduce((a,l)=>a+l.duration,0)){if(!laps.length)return;const name=prompt('Nome da sessão:',`${type==='video'?'Vídeo':'Treino'} ${new Date().toLocaleDateString('pt-BR')} - ${state.robot}`);if(!name)return;const data=sessions();data.unshift({id:(crypto.randomUUID?crypto.randomUUID():String(Date.now())),name,robot:state.robot,type,createdAt:new Date().toISOString(),laps:laps.map(l=>typeof l==='number'?l:l.duration),total});saveSessions(data);toast('Sessão salva com sucesso');renderHomeStats();return true}
function renderHistory(){const list=$('#history-list'),data=sessions().filter(s=>state.historyFilter==='all'||s.type===state.historyFilter);$$('.filter').forEach(b=>b.classList.toggle('active',b.dataset.filter===state.historyFilter));if(!data.length){list.innerHTML='<div class="empty-state"><span>▤</span><p>Nenhuma sessão encontrada neste filtro.</p></div>';return}list.innerHTML=data.map(s=>{const best=Math.min(...s.laps),avg=s.laps.reduce((a,v)=>a+v,0)/s.laps.length;const r=ROBOTS[s.robot]||ROBOTS.Zhort;return `<article class="history-card"><header><strong><i style="color:${r.color}">●</i> ${escapeHtml(s.name)}</strong><small>${new Date(s.createdAt).toLocaleDateString('pt-BR')}</small></header><div class="history-meta">${s.robot} · ${s.type==='video'?'VÍDEO':'MANUAL'} · ${s.laps.length} VOLTAS · MELHOR ${format(best)} · MÉDIA ${format(avg)}</div><div class="history-actions"><button data-export="${s.id}">Exportar CSV</button><button data-share="${s.id}" class="share-button">Compartilhar</button><button data-rename="${s.id}">Renomear</button><button data-delete="${s.id}">Excluir</button></div></article>`}).join('');$$('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('Excluir esta sessão?')){saveSessions(sessions().filter(s=>s.id!==b.dataset.delete));renderHistory();renderHomeStats()}});$$('[data-rename]').forEach(b=>b.onclick=()=>{const data=sessions(),s=data.find(x=>x.id===b.dataset.rename),name=prompt('Novo nome:',s.name);if(name){s.name=name;saveSessions(data);renderHistory()}});$$('[data-export]').forEach(b=>b.onclick=()=>exportSession(sessions().find(s=>s.id===b.dataset.export)));$$('[data-share]').forEach(b=>b.onclick=()=>shareSession(sessions().find(s=>s.id===b.dataset.share)))}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function exportSession(s){if(!s)return;const csv=['sessao,robo,tipo,volta,tempo_ms,tempo_formatado',...s.laps.map((v,i)=>`"${String(s.name).replace(/"/g,'""')}",${s.robot},${s.type},${i+1},${v},${format(v)}`)].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`${s.name.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
async function shareSession(s){if(!s)return;const text=`${s.name} · ${s.robot}\n${s.laps.length} voltas · melhor ${format(Math.min(...s.laps))} · total ${format(s.total)}`;try{if(navigator.share)await navigator.share({title:s.name,text});else{await navigator.clipboard.writeText(text);toast('Resumo copiado para compartilhar')}}catch(e){if(e.name!=='AbortError')toast('Não foi possível compartilhar neste navegador')}}

function sessionOptions(){return sessions().filter(s=>s.laps?.length)}
function renderComparison(){const all=sessionOptions(),wrap=$('#compare-selectors');if(!all.length){wrap.innerHTML='<div class="compare-empty">Salve pelo menos uma sessão com voltas para gerar a comparação.</div>';drawEmptyCharts();$('#compare-table').innerHTML='';return}const byRobot=Object.keys(ROBOTS).map(robot=>[robot,all.filter(s=>s.robot===robot)]);wrap.innerHTML=byRobot.map(([robot,list])=>`<label>${robot}<select data-compare="${robot}"><option value="">Selecionar sessão</option>${list.map(s=>`<option value="${s.id}">${escapeHtml(s.name)} · ${s.laps.length} voltas</option>`).join('')}</select></label>`).join('');byRobot.forEach(([robot,list])=>{const selected=localStorage.getItem(`zrv-compare-${robot}`),sel=$(`[data-compare="${robot}"]`);if(selected&&list.some(s=>s.id===selected))sel.value=selected;else if(list[0])sel.value=list[0].id;sel.onchange=()=>{localStorage.setItem(`zrv-compare-${robot}`,sel.value);drawComparison()}});drawComparison()}
function selectedComparison(){return Object.keys(ROBOTS).map(robot=>{const id=$(`[data-compare="${robot}"]`)?.value;return id?sessions().find(s=>s.id===id):null}).filter(Boolean)}
function prepareCanvas(canvas,height){const ratio=Math.max(1,window.devicePixelRatio||1),width=canvas.clientWidth||320;canvas.width=width*ratio;canvas.height=height*ratio;const ctx=canvas.getContext('2d');ctx.scale(ratio,ratio);return{ctx,width,height}}
function drawEmptyCharts(){['#lap-chart','#best-chart'].forEach((id,i)=>{const {ctx,width,height}=prepareCanvas($(id),i?190:220);ctx.fillStyle=getComputedStyle(document.documentElement).getPropertyValue('--muted');ctx.font='12px Manrope';ctx.textAlign='center';ctx.fillText('Selecione sessões para visualizar o gráfico',width/2,height/2)})}
function drawComparison(){const selected=selectedComparison();drawLapChart(selected);drawBestChart(selected);renderCompareTable(selected);$('#lap-legend').innerHTML=selected.map(s=>`<span><i style="background:${ROBOTS[s.robot].color}"></i>${s.robot}</span>`).join('')}
function drawLapChart(data){const {ctx,width,height}=prepareCanvas($('#lap-chart'),220),styles=getComputedStyle(document.body),muted=styles.getPropertyValue('--muted'),line=styles.getPropertyValue('--line');ctx.clearRect(0,0,width,height);if(!data.length){drawEmptyCharts();return}const pad={l:34,r:10,t:14,b:28},maxL=Math.max(...data.map(s=>s.laps.length)),maxV=Math.max(...data.flatMap(s=>s.laps))/1000*1.12||1;ctx.font='9px DM Mono';ctx.strokeStyle=line;ctx.fillStyle=muted;ctx.textAlign='right';for(let i=0;i<4;i++){const y=pad.t+(height-pad.t-pad.b)*i/3;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(width-pad.r,y);ctx.stroke();ctx.fillText((maxV*(1-i/3)).toFixed(1),pad.l-5,y+3)}data.forEach(s=>{const color=ROBOTS[s.robot].color;ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=2;ctx.beginPath();s.laps.forEach((v,i)=>{const x=pad.l+(width-pad.l-pad.r)*(maxL===1?0:i/(maxL-1));const y=pad.t+(height-pad.t-pad.b)*(1-v/1000/maxV);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();s.laps.forEach((v,i)=>{const x=pad.l+(width-pad.l-pad.r)*(maxL===1?0:i/(maxL-1));const y=pad.t+(height-pad.t-pad.b)*(1-v/1000/maxV);ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fill()})});ctx.fillStyle=muted;ctx.textAlign='center';for(let i=0;i<maxL;i++)ctx.fillText(`#${i+1}`,pad.l+(width-pad.l-pad.r)*(maxL===1?0:i/(maxL-1)),height-9)}
function drawBestChart(data){const {ctx,width,height}=prepareCanvas($('#best-chart'),190),styles=getComputedStyle(document.body),muted=styles.getPropertyValue('--muted'),line=styles.getPropertyValue('--line');ctx.clearRect(0,0,width,height);if(!data.length)return;const pad={l:33,r:10,t:12,b:32},maxV=Math.max(...data.map(s=>Math.min(...s.laps)))/1000*1.25||1;ctx.strokeStyle=line;ctx.font='9px DM Mono';ctx.fillStyle=muted;ctx.textAlign='right';for(let i=0;i<3;i++){const y=pad.t+(height-pad.t-pad.b)*i/2;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(width-pad.r,y);ctx.stroke();ctx.fillText((maxV*(1-i/2)).toFixed(1),pad.l-5,y+3)}const slot=(width-pad.l-pad.r)/data.length;data.forEach((s,i)=>{const v=Math.min(...s.laps)/1000,x=pad.l+slot*i+slot*.2,w=slot*.6,h=(height-pad.t-pad.b)*v/maxV;ctx.fillStyle=ROBOTS[s.robot].color;ctx.fillRect(x,height-pad.b-h,w,h);ctx.fillStyle=muted;ctx.textAlign='center';ctx.fillText(s.robot,x+w/2,height-17);ctx.fillText(v.toFixed(2)+'s',x+w/2,height-pad.b-h-5)})}
function renderCompareTable(data){const el=$('#compare-table');if(!data.length){el.innerHTML='<div class="compare-empty">Nenhuma sessão selecionada.</div>';return}const metrics=[['Melhor volta',s=>Math.min(...s.laps)],['Média',s=>s.laps.reduce((a,v)=>a+v,0)/s.laps.length],['Tempo total',s=>s.total||s.laps.reduce((a,v)=>a+v,0)],['Número de voltas',s=>s.laps.length]],rows=metrics.map(([label,fn])=>{const vals=data.map(fn),best=label==='Número de voltas'?Math.max(...vals):Math.min(...vals);return `<tr><td>${label}</td>${data.map((s,i)=>`<td class="${vals[i]===best?'fastest':''}">${label==='Número de voltas'?vals[i]:format(vals[i])}</td>`).join('')}</tr>`}).join('');el.innerHTML=`<table class="comparison-table"><thead><tr><th>Métrica</th>${data.map(s=>`<th style="color:${ROBOTS[s.robot].color}">${s.robot}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table>`}

async function openCamera(){const v=$('#camera-video');if(!navigator.mediaDevices?.getUserMedia){toast('Este navegador não oferece câmera. Abra o app em HTTPS.');return}try{if(state.video.stream)stopCamera();state.video.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:state.video.facing},width:{ideal:1280},height:{ideal:720}},audio:true});v.srcObject=state.video.stream;state.video.cameraOn=true;$('#camera-empty').hidden=true;$('#camera-button').textContent='Fechar câmera';$('#flip-camera').disabled=false;$('#video-start').disabled=false;$('#video-manual-lap').disabled=false;$('#camera-help').textContent='Câmera pronta. Ajuste a linha de chegada e inicie a detecção.';drawCameraOverlay()}catch(e){toast(e.name==='NotAllowedError'?'Permita o acesso à câmera nas configurações do navegador.':'Câmera indisponível: use HTTPS ou localhost.')}}
function stopCamera(){if(state.video.stream)state.video.stream.getTracks().forEach(t=>t.stop());state.video.stream=null;state.video.cameraOn=false;state.video.running=false;$('#camera-video').srcObject=null;$('#camera-empty').hidden=false;$('#camera-button').textContent='Abrir câmera';$('#flip-camera').disabled=true;$('#video-start').disabled=true;$('#video-manual-lap').disabled=true;cancelAnimationFrame(state.video.raf)}
function drawCameraOverlay(){const c=$('#camera-overlay'),box=c.getBoundingClientRect(),ratio=window.devicePixelRatio||1;c.width=box.width*ratio;c.height=box.height*ratio;const ctx=c.getContext('2d');ctx.scale(ratio,ratio);ctx.clearRect(0,0,box.width,box.height);const y=box.height*state.video.line;ctx.strokeStyle=ROBOTS[state.robot].color;ctx.lineWidth=2;ctx.setLineDash([8,6]);ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(box.width,y);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=ROBOTS[state.robot].color;ctx.font='10px DM Mono';ctx.fillText('ZONA DE CHEGADA',10,Math.max(14,y-8))}
function videoNow(){return state.video.running&&!state.video.waitingForStart?performance.now()-state.video.startedAt:state.video.elapsed}
function updateVideoHud(){const total=videoNow(),laps=state.video.laps,previous=laps.reduce((a,v)=>a+v,0);$('#video-total').textContent=format(total);$('#video-lap-number').textContent=laps.length;$('#video-current-lap').textContent=format(Math.max(0,total-previous));$('#video-state').textContent=state.video.running?(state.video.waitingForStart?'AGUARDANDO 1ª PASSAGEM':'CRONOMETRANDO'):(state.video.cameraOn?'PRONTO':'CÂMERA OFF');if(state.video.running)state.video.raf=requestAnimationFrame(updateVideoHud)}
function startVideoSession(){if(!state.video.cameraOn)return openCamera();state.video.laps=[];state.video.elapsed=0;state.video.startedAt=0;state.video.waitingForStart=true;state.video.running=true;state.video.lastFrame=null;state.video.lastDetection=performance.now();$('#video-state').textContent='AGUARDANDO 1ª PASSAGEM';$('#video-start').disabled=true;$('#video-stop').disabled=false;$('#video-manual-lap').disabled=false;$('#camera-help').textContent='A 1ª passagem inicia o cronômetro. A 2ª passagem registra a primeira volta; cada passagem seguinte fecha outra volta.';startRecording();updateVideoHud();detectFrame()}
function addVideoLap(){if(!state.video.running)return;if(state.video.waitingForStart){state.video.startedAt=performance.now();state.video.waitingForStart=false;beep();toast('1ª passagem detectada · cronômetro iniciado');updateVideoHud();return}const total=performance.now()-state.video.startedAt,prev=state.video.laps.reduce((a,v)=>a+v,0);state.video.laps.push(total-prev);beep();toast(`Volta ${state.video.laps.length} · ${format(total-prev)}`);updateVideoHud()}
function stopVideoSession(save=true){if(!state.video.running&&!state.video.laps.length)return;state.video.elapsed=state.video.waitingForStart?0:videoNow();state.video.running=false;cancelAnimationFrame(state.video.raf);if(state.video.recorder&&state.video.recorder.state!=='inactive')state.video.recorder.stop();$('#video-start').disabled=!state.video.cameraOn;$('#video-stop').disabled=true;$('#video-manual-lap').disabled=!state.video.cameraOn;updateVideoHud();if(save&&state.video.laps.length)saveSession(state.video.laps,'video',state.video.laps.reduce((a,v)=>a+v,0))}
function startRecording(){state.video.chunks=[];try{const options=MediaRecorder.isTypeSupported('video/webm;codecs=vp9,opus')?{mimeType:'video/webm;codecs=vp9,opus'}:{};state.video.recorder=new MediaRecorder(state.video.stream,options);state.video.recorder.ondataavailable=e=>{if(e.data.size)state.video.chunks.push(e.data)};state.video.recorder.onstop=()=>{if(!state.video.chunks.length)return;const url=URL.createObjectURL(new Blob(state.video.chunks,{type:state.video.recorder.mimeType||'video/webm'}));$('#recorded-video').src=url;$('#recording-review').hidden=false};state.video.recorder.start(250)}catch{toast('Gravação não suportada; a detecção ainda pode ser usada.')}}
function detectFrame(){if(!state.video.running)return;const v=$('#camera-video'),c=document.createElement('canvas');c.width=160;c.height=90;const ctx=c.getContext('2d',{willReadFrequently:true});let last=state.video.lastFrame;const sample=()=>{if(!state.video.running||v.readyState<2){state.video.raf=requestAnimationFrame(sample);return}ctx.drawImage(v,0,0,c.width,c.height);const y=Math.round(c.height*state.video.line),band=6,img=ctx.getImageData(0,Math.max(0,y-band),c.width,band*2),gray=new Uint8Array(c.width*band*2);let sum=0;for(let i=0,j=0;i<img.data.length;i+=4,j++){gray[j]=(img.data[i]*.299+img.data[i+1]*.587+img.data[i+2]*.114);sum+=gray[j]}if(last){let diff=0;for(let i=0;i<gray.length;i++)diff+=Math.abs(gray[i]-last[i]);diff/=gray.length;if(diff>18&&performance.now()-state.video.lastDetection>1800){state.video.lastDetection=performance.now();addVideoLap()}}state.video.lastFrame=gray;state.video.raf=requestAnimationFrame(sample)};sample()}
function beep(){if(!state.sound)return;try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.frequency.value=720;g.gain.setValueAtTime(.08,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.13);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.13)}catch{}}
let toastTimer;function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2600)}
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>showScreen(b.dataset.go)));$('#start-pause').onclick=startPause;$('#lap-button').onclick=recordLap;$('#reset-button').onclick=()=>{if(state.elapsed||state.laps.length){if(confirm('Resetar o cronômetro e as voltas?'))resetTimer()}else resetTimer()};$('#save-session-button').onclick=()=>saveSession();$('#theme-button').onclick=()=>document.body.classList.toggle('light');$('#sound-toggle').onclick=()=>{state.sound=!state.sound;localStorage.setItem('zrv-sound',state.sound?'on':'off');$('#sound-toggle').classList.toggle('on',state.sound)};$('#export-all').onclick=()=>{const all=sessions();if(!all.length){toast('Não há sessões para exportar');return}all.forEach((s,i)=>setTimeout(()=>exportSession(s),i*250));toast('Exportando sessões CSV')};$$('.filter').forEach(b=>b.onclick=()=>{state.historyFilter=b.dataset.filter;renderHistory()});$('#camera-button').onclick=()=>state.video.cameraOn?stopCamera():openCamera();$('#flip-camera').onclick=async()=>{state.video.facing=state.video.facing==='environment'?'user':'environment';await openCamera()};$('#video-start').onclick=startVideoSession;$('#video-manual-lap').onclick=addVideoLap;$('#video-stop').onclick=()=>stopVideoSession(true);$('#finish-line').oninput=e=>{state.video.line=Number(e.target.value)/100;$('#finish-position').textContent=`${e.target.value}%`;drawCameraOverlay()};$('#camera-overlay').onclick=e=>{const r=e.currentTarget.getBoundingClientRect();state.video.line=Math.max(.15,Math.min(.85,(e.clientY-r.top)/r.height));$('#finish-line').value=Math.round(state.video.line*100);$('#finish-position').textContent=`${Math.round(state.video.line*100)}%`;drawCameraOverlay();toast('Zona de chegada posicionada')};window.addEventListener('resize',drawCameraOverlay);document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.running)startPause()});
renderRobots();updateRobotUI();updateTimer();renderLaps();
let deferredInstall;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#install-button').hidden=false});$('#install-button').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();deferredInstall=null}};if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));

