const ROBOTS={Zhort:{color:'#46a5ff',rgb:'70,165,255',initial:'Z'},Rios:{color:'#6ddb9a',rgb:'109,219,154',initial:'R'},Vendra:{color:'#ffad5e',rgb:'255,173,94',initial:'V'}};
const storeKey='zrv-lap-sessions';
const state={robot:localStorage.getItem('zrv-robot')||'Zhort',screen:'home',running:false,startedAt:0,elapsed:0,lastLapAt:0,laps:[],raf:0,sound:true};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function format(ms){const total=Math.max(0,Math.round(ms));const m=Math.floor(total/60000);const s=Math.floor(total%60000/1000);const t=total%1000;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${String(t).padStart(3,'0')}`}
function sessions(){try{return JSON.parse(localStorage.getItem(storeKey)||'[]')}catch{return[]}}
function saveSessions(data){localStorage.setItem(storeKey,JSON.stringify(data))}
function robotPill(el){const r=ROBOTS[state.robot];el.innerHTML=`<i style="background:${r.color}"></i><span>${state.robot}</span>`;el.style.color=r.color;el.style.background=`rgba(${r.rgb},.12)`}
function renderRobots(){const wrap=$('#robot-selector');wrap.innerHTML=Object.entries(ROBOTS).map(([name,r])=>`<button type="button" class="robot-card ${name===state.robot?'selected':''}" style="--robot:${r.color};--robot-rgb:${r.rgb}" data-robot="${name}"><span class="robot-orb">${r.initial}</span><strong>${name}</strong><small>${name==='Zhort'?'Azul':name==='Rios'?'Verde':'Laranja'}</small></button>`).join('');$$('[data-robot]').forEach(b=>b.onclick=()=>{state.robot=b.dataset.robot;localStorage.setItem('zrv-robot',state.robot);renderRobots();updateRobotUI();toast(`${state.robot} selecionado`);});}
function updateRobotUI(){['#manual-robot-pill','#video-robot-pill'].forEach(s=>robotPill($(s)));const r=ROBOTS[state.robot];document.documentElement.style.setProperty('--accent',r.color);document.documentElement.style.setProperty('--accent-rgb',r.rgb);renderHomeStats();}
function renderHomeStats(){const all=sessions();$('#home-stats').textContent=all.length?`${all.length} sessão${all.length>1?'ões':''} salva${all.length>1?'s':''} neste aparelho`:'NENHUMA SESSÃO SALVA AINDA';}
function showScreen(name){state.screen=name;$$('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===name));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.go===name||(name==='manual'&&b.classList.contains('central'))));if(name==='history')renderHistory();if(name==='home')renderHomeStats();window.scrollTo({top:0,behavior:'smooth'});}
function updateTimer(){const now=state.running?performance.now()-state.startedAt:state.elapsed;const display=format(now);$('#timer-display').innerHTML=display.slice(0,-4)+`<span>${display.slice(-4)}</span>`;$('#timer-total').textContent=display;$('#timer-status').textContent=state.running?'CRONOMETRANDO':'PAUSADO';$('#timer-status-dot').classList.toggle('running',state.running);$('#timer-lap-count').textContent=`${state.laps.length} VOLTA${state.laps.length===1?'':'S'}`;$('#start-pause').querySelector('span').textContent=state.running?'Ⅱ':'▶';$('#start-pause').querySelector('strong').textContent=state.running?'Pausar':'Iniciar';$('#lap-button').disabled=!state.running;$('#save-session-button').disabled=state.laps.length===0; if(state.running)state.raf=requestAnimationFrame(updateTimer)}
function startPause(){if(state.running){state.elapsed=performance.now()-state.startedAt;state.running=false;cancelAnimationFrame(state.raf)}else{state.startedAt=performance.now()-state.elapsed;state.running=true}updateTimer()}
function recordLap(){if(!state.running)return;const total=performance.now()-state.startedAt;const previous=state.laps.reduce((a,l)=>a+l.duration,0);state.laps.push({duration:total-previous,total});renderLaps();beep();}
function renderLaps(){const list=$('#laps-list');if(!state.laps.length){list.innerHTML='<div class="empty-state"><span>＋</span><p>Inicie o cronômetro e toque em<br><strong>Volta</strong> ao cruzar a linha.</p></div>';$('#laps-best').textContent='MELHOR —';return}const best=Math.min(...state.laps.map(l=>l.duration));$('#laps-best').textContent=`MELHOR ${format(best)}`;list.innerHTML=[...state.laps].reverse().map((l,i)=>`<div class="lap-row ${l.duration===best?'best':''}"><span class="lap-number">#${state.laps.length-i}</span><span class="lap-time">${format(l.duration)}</span>${l.duration===best?'<span class="best-label">MELHOR</span>':''}</div>`).join('')}
function resetTimer(){state.running=false;cancelAnimationFrame(state.raf);state.elapsed=0;state.laps=[];updateTimer();renderLaps();}
function saveSession(){const name=prompt('Nome da sessão:',`Treino ${new Date().toLocaleDateString('pt-BR')} - ${state.robot}`);if(!name)return;const data=sessions();data.unshift({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),name,robot:state.robot,type:'manual',createdAt:new Date().toISOString(),laps:state.laps.map(l=>l.duration),total:state.laps.reduce((a,l)=>a+l.duration,0)});saveSessions(data);toast('Sessão salva com sucesso');renderHomeStats();}
function renderHistory(){const list=$('#history-list'), data=sessions();if(!data.length){list.innerHTML='<div class="empty-state"><span>▤</span><p>As sessões que você salvar aparecerão aqui.</p></div>';return}list.innerHTML=data.map(s=>{const best=Math.min(...s.laps),avg=s.laps.reduce((a,v)=>a+v,0)/s.laps.length;const r=ROBOTS[s.robot]||ROBOTS.Zhort;return `<article class="history-card"><header><strong><i style="color:${r.color}">●</i> ${s.name}</strong><small>${new Date(s.createdAt).toLocaleDateString('pt-BR')}</small></header><div class="history-meta">${s.laps.length} VOLTAS · MELHOR ${format(best)} · MÉDIA ${format(avg)}</div><div class="history-actions"><button data-export="${s.id}">Exportar CSV</button><button data-delete="${s.id}">Excluir</button></div></article>`}).join('');$$('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('Excluir esta sessão?')){saveSessions(data.filter(s=>s.id!==b.dataset.delete));renderHistory();renderHomeStats()}});$$('[data-export]').forEach(b=>b.onclick=()=>exportSession(data.find(s=>s.id===b.dataset.export)))}
function exportSession(s){const csv=['sessao,robo,volta,tempo_ms,tempo_formatado',...s.laps.map((v,i)=>`"${s.name}",${s.robot},${i+1},${v},${format(v)}`)].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`${s.name.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}.csv`;a.click();URL.revokeObjectURL(a.href);}
function beep(){if(!state.sound)return;try{const c=new AudioContext(),o=c.createOscillator(),g=c.createGain();o.frequency.value=720;g.gain.setValueAtTime(.08,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.13);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.13)}catch{}}
let toastTimer;function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2300)}
$$('[data-go]').forEach(b=>b.addEventListener('click',()=>showScreen(b.dataset.go)));$('#start-pause').onclick=startPause;$('#lap-button').onclick=recordLap;$('#reset-button').onclick=()=>{if(state.elapsed||state.laps.length){if(confirm('Resetar o cronômetro e as voltas?'))resetTimer()}else resetTimer()};$('#save-session-button').onclick=saveSession;$('#theme-button').onclick=()=>document.body.classList.toggle('light');$$('[data-toast]').forEach(b=>b.onclick=()=>toast(b.dataset.toast));$('#sound-toggle').onclick=()=>{state.sound=!state.sound;$('#sound-toggle').classList.toggle('on',state.sound)};$('#export-all').onclick=()=>{sessions().forEach((s,i)=>setTimeout(()=>exportSession(s),i*250));if(sessions().length)toast('Exportando sessões CSV')};
renderRobots();updateRobotUI();updateTimer();renderLaps();
let deferredInstall;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#install-button').hidden=false});$('#install-button').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();deferredInstall=null}};
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));

